#!/usr/bin/env python3
"""Build a paired macOS service / WorkBuddy Skill bundle (build-host tools only)."""
import argparse
import datetime
import hashlib
import json
import os
from pathlib import Path
import platform
import plistlib
import re
import shutil
import stat
import struct
import subprocess
import tempfile
import uuid
import zipfile

ROOT = Path(__file__).resolve().parents[1]
APP_PAYLOAD = 'payload/app'
APP_SERVICE = APP_PAYLOAD + '/Contents/MacOS/cosmoedge-connect'
PLUGIN_SOURCE = 'integrations/workbuddy/plugins/summary-report-guard'
PLUGIN_PAYLOAD = 'payload/workbuddy-plugin'
PLUGIN_NAME = 'cosmoedge-summary-report-guard'
PLUGIN_RELATIVE = 'plugins/' + PLUGIN_NAME
MARKETPLACE_NAME = 'cosmoedge-summary-report-guard-local'


def run(*args):
    return subprocess.check_output(args, cwd=ROOT, text=True).strip()


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_inventory():
    paths = run('git', 'ls-files', '-z', '--cached', '--others', '--exclude-standard').split('\0')
    files = []
    for name in sorted(set(paths)):
        path = ROOT / name
        if path.is_symlink():
            target = os.readlink(path)
            files.append({'path': name, 'kind': 'symlink', 'target': target,
                          'sha256': hashlib.sha256(target.encode()).hexdigest()})
        elif path.is_file():
            files.append({'path': name, 'sha256': digest(path)})
    return files


def plugin_tree(path):
    """Never dereference source links while building an executable host plugin."""
    info = path.lstat()
    if stat.S_ISLNK(info.st_mode) or not (stat.S_ISDIR(info.st_mode) or stat.S_ISREG(info.st_mode)):
        raise ValueError('WorkBuddy plugin source must contain only regular files and directories')
    if stat.S_ISREG(info.st_mode) and info.st_nlink != 1:
        raise ValueError('WorkBuddy plugin source cannot contain hard links')
    if stat.S_ISDIR(info.st_mode):
        for child in path.iterdir():
            plugin_tree(child)


def read_plugin_source():
    source = ROOT
    for part in Path(PLUGIN_SOURCE).parts:
        source = source / part
        if source.is_symlink() or not source.is_dir():
            raise ValueError('Required WorkBuddy plugin source is missing or linked')
    plugin_tree(source)
    market = json.loads((source / '.codebuddy-plugin/marketplace.json').read_text())
    plugin = json.loads((source / PLUGIN_RELATIVE / '.codebuddy-plugin/plugin.json').read_text())
    entries = market.get('plugins') if isinstance(market, dict) else None
    if (not isinstance(plugin, dict) or plugin.get('name') != PLUGIN_NAME
            or not isinstance(plugin.get('version'), str)
            or not re.fullmatch(r'(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)', plugin['version'])
            or not isinstance(market, dict) or market.get('name') != MARKETPLACE_NAME or not isinstance(entries, list) or len(entries) != 1
            or not isinstance(entries[0], dict) or entries[0].get('name') != PLUGIN_NAME
            or entries[0].get('source') != './' + PLUGIN_RELATIVE
            or entries[0].get('version') != plugin['version']):
        raise ValueError('Unsupported WorkBuddy marketplace or plugin identity')
    for name in ('hooks/hooks.json', 'scripts/post_read.py'):
        if not (source / PLUGIN_RELATIVE / name).is_file():
            raise ValueError('Required WorkBuddy plugin material is missing')
    if (source / PLUGIN_RELATIVE / 'candidate.json').exists():
        raise ValueError('WorkBuddy plugin candidate identity must be generated by this build')
    return source, market, plugin


def package_workbuddy_plugin(stage, candidate, source_material):
    source, market, plugin = source_material
    destination = stage / PLUGIN_PAYLOAD
    # Preserve links if a concurrent replacement occurs, then reject them;
    # copytree must never follow one into material outside the source tree.
    shutil.copytree(source, destination, symlinks=True)
    plugin_tree(destination)
    source_version = plugin['version']
    identity = hashlib.sha256(json.dumps(candidate, sort_keys=True, separators=(',', ':')).encode()).hexdigest()
    version = source_version + '-paired.c' + identity[:20]
    plugin['version'] = version
    market['plugins'][0]['version'] = version
    (destination / '.codebuddy-plugin/marketplace.json').write_text(json.dumps(market, indent=2, ensure_ascii=False) + '\n')
    (destination / PLUGIN_RELATIVE / '.codebuddy-plugin/plugin.json').write_text(json.dumps(plugin, indent=2, ensure_ascii=False) + '\n')
    (destination / PLUGIN_RELATIVE / 'candidate.json').write_text(json.dumps({'schemaVersion': 1, 'candidate': candidate}, indent=2) + '\n')
    return {'schemaVersion': 1, 'name': PLUGIN_NAME, 'version': version, 'sourceVersion': source_version,
            'marketplaceName': MARKETPLACE_NAME, 'sourceDirectory': PLUGIN_SOURCE,
            'payloadPath': PLUGIN_PAYLOAD, 'pluginPath': PLUGIN_PAYLOAD + '/' + PLUGIN_RELATIVE,
            'requiresNativeInstallAndEnable': True}


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--version', required=True)
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--arch', choices=['arm64', 'amd64'], default='arm64' if platform.machine() == 'arm64' else 'amd64')
    parser.add_argument('--with-mcp', action='store_true', help='include the paired local stdio MCP adapter')
    parser.add_argument('--allow-dirty', action='store_true', help='explicit development bundle; manifest records dirty source')
    parser.add_argument('--with-summary-report-guard', action='store_true',
                        help='include the paired report Read plugin for native host validation')
    signing = parser.add_mutually_exclusive_group(required=True)
    signing.add_argument('--development-app', action='store_true', help='build an explicitly development-only ad hoc signed macOS app')
    signing.add_argument('--signing-identity', help='Apple-issued code-signing identity, selected by its 40-digit SHA1 fingerprint')
    parser.add_argument('--app-build-version', default='1.0.0', help='numeric CFBundleVersion (default: 1.0.0)')
    args = parser.parse_args(argv)
    if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9._-]{0,79}', args.version):
        parser.error('version must be a short filename-safe identifier')
    if args.signing_identity is not None and not re.fullmatch(r'[0-9A-Fa-f]{40}', args.signing_identity):
        parser.error('signing identity must be an exact 40-digit SHA1 fingerprint')
    if not re.fullmatch(r'[1-9][0-9]{0,3}(?:\.(?:0|[1-9][0-9]?)){0,2}', args.app_build_version):
        parser.error('app build version must contain one to three numeric components (major 1-9999, minor and patch 0-99)')
    if (args.development_app or args.signing_identity) and platform.system() != 'Darwin':
        parser.error('macOS app signing requires a macOS build host')
    return args


def app_build_id(revision, version, bundle_id, arch, source_digest, binary_digest):
    # A different app identity must not reuse another app's Mach-O LC_UUID.
    inputs = {'revision': revision, 'version': version, 'bundleIdentifier': bundle_id,
              'arch': arch, 'sourceDigest': source_digest, 'unsignedBinaryDigest': binary_digest}
    return hashlib.sha256(json.dumps(inputs, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def macho_build_uuid(path, arch):
    """Read the actual thin Mach-O UUID; a Go build ID is not this evidence."""
    raw = path.read_bytes()
    if len(raw) < 32 or raw[:4] != b'\xcf\xfa\xed\xfe':
        raise ValueError('app executable must be a little-endian 64-bit Mach-O')
    _, cpu, _, filetype, count, commands_size, _, _ = struct.unpack_from('<8I', raw)
    if cpu != {'arm64': 0x100000c, 'amd64': 0x1000007}[arch] or filetype != 2:
        raise ValueError('app executable architecture or Mach-O type is incorrect')
    end, offset, values = 32 + commands_size, 32, []
    if end > len(raw) or count > commands_size // 8:
        raise ValueError('app executable load commands are truncated')
    for _ in range(count):
        if offset + 8 > end:
            raise ValueError('app executable load command is truncated')
        command, size = struct.unpack_from('<2I', raw, offset)
        if size < 8 or offset + size > end:
            raise ValueError('app executable load command has an invalid size')
        if command == 0x1b:  # LC_UUID
            if size != 24:
                raise ValueError('app executable UUID command is malformed')
            values.append(uuid.UUID(bytes=raw[offset + 8:offset + 24]))
        offset += size
    if offset != end or len(values) != 1 or values[0].int == 0:
        raise ValueError('app executable must contain exactly one nonzero Mach-O build UUID')
    return str(values[0]).upper()


def sign_app(app, service, args, bundle_id):
    build_uuid = macho_build_uuid(service, args.arch)
    identity = args.signing_identity.upper() if args.signing_identity else '-'
    subprocess.run(['/usr/bin/codesign', '--force', '--sign', identity, '--identifier', bundle_id, str(app)],
                   check=True, capture_output=True, text=True)
    verify = ['/usr/bin/codesign', '--verify', '--strict']
    if args.signing_identity:
        # A matching hash alone can also select a self-signed identity.
        verify.extend(['--test-requirement', 'anchor apple generic'])
    subprocess.run(verify + [str(app)], check=True, capture_output=True, text=True)
    display = subprocess.run(['/usr/bin/codesign', '--display', '--verbose=4', str(app)],
                             check=True, capture_output=True, text=True)
    details = display.stdout + '\n' + display.stderr
    identifier = re.search(r'^Identifier=(.+)$', details, re.MULTILINE)
    team = re.search(r'^TeamIdentifier=(.+)$', details, re.MULTILINE)
    adhoc = re.search(r'^Signature=adhoc$', details, re.MULTILINE) is not None
    if not identifier or identifier.group(1) != bundle_id:
        raise ValueError('signed app identifier does not match its bundle identity')
    team_id = team.group(1) if team and team.group(1) != 'not set' else None
    if args.signing_identity:
        if adhoc or not team_id or not re.fullmatch(r'[A-Z0-9]{10}', team_id):
            raise ValueError('Apple signing requires a verified Team Identifier')
    elif not adhoc or team_id is not None:
        raise ValueError('development app must have an ad hoc signature without a Team Identifier')
    if macho_build_uuid(service, args.arch) != build_uuid:
        raise ValueError('app build UUID changed during signing')
    return {'payloadPath': APP_PAYLOAD, 'bundleIdentifier': bundle_id,
            'signing': 'apple' if args.signing_identity else 'development-adhoc',
            'teamIdentifier': team_id, 'buildUUID': build_uuid}


def main(argv=None):
    args = parse_args(argv)
    output = args.output.expanduser().absolute()
    if output == ROOT or ROOT in output.parents:
        raise ValueError('build output must be outside the source worktree')
    if output.exists():
        raise ValueError('output already exists; choose a new candidate directory')
    revision = run('git', 'rev-parse', 'HEAD')
    tree = run('git', 'rev-parse', 'HEAD^{tree}')
    dirty = bool(run('git', 'status', '--porcelain', '--untracked-files=normal'))
    if dirty and not args.allow_dirty:
        raise ValueError('source is modified; commit it or explicitly use --allow-dirty')
    # Bind the exact build inputs, including tracked modifications and untracked source.
    source_files = source_inventory()
    source_digest = hashlib.sha256(json.dumps(source_files, sort_keys=True, separators=(',', ':')).encode()).hexdigest()
    plugin_source = read_plugin_source() if args.with_summary_report_guard else None
    output.parent.mkdir(parents=True, exist_ok=True)
    stage = Path(tempfile.mkdtemp(prefix='.cosmoedge-connect-build-', dir=output.parent))
    try:
        service_metadata = {'entrypoint': './cmd/cosmoedge-connect', 'healthProtocol': 'cosmoedge.operations.v1'}
        # Bind executable identity to the same Git snapshot as the manifest.
        # Go VCS discovery can omit .git-file worktrees even with buildvcs=true.
        ldflags = ('-X github.com/cosmo-wander-ai/cosmoedge-connect/internal/buildinfo.Version=' + args.version
                   + ' -X github.com/cosmo-wander-ai/cosmoedge-connect/internal/buildinfo.SourceRevision=' + revision
                   + ' -X github.com/cosmo-wander-ai/cosmoedge-connect/internal/buildinfo.SourceModified=' + str(dirty).lower())
        bundle_id = 'com.cosmoedge.connect' + ('.development' if args.development_app else '')
        app_name = 'CosmoEdge Connect' + (' Development' if args.development_app else '')
        app = stage / 'payload' / (app_name + '.app')
        service = app / 'Contents/MacOS/cosmoedge-connect'
        service.parent.mkdir(parents=True)
        info = {'CFBundleIdentifier': bundle_id, 'CFBundleExecutable': 'cosmoedge-connect', 'CFBundlePackageType': 'APPL',
                'CFBundleName': app_name, 'CFBundleDisplayName': app_name, 'CFBundleInfoDictionaryVersion': '6.0',
                'CFBundleVersion': args.app_build_version,
                'CFBundleShortVersionString': '.'.join((args.app_build_version.split('.') + ['0', '0'])[:3]),
                'LSUIElement': True,
                'NSLocalNetworkUsageDescription': '连接您选择的局域网 CosmoEdge 设备，读取设备与视频源状态，并执行您确认的现场任务和画面观察。'}
        (app / 'Contents/Info.plist').write_bytes(plistlib.dumps(info))
        (app / 'Contents/Info.plist').chmod(0o644)
        env = dict(os.environ, GOOS='darwin', GOARCH=args.arch, CGO_ENABLED='0', GOWORK='off', GOFLAGS='')
        subprocess.run(['go', 'build', '-trimpath', '-buildvcs=true', '-ldflags', ldflags,
                        '-o', str(service), './cmd/cosmoedge-connect'], cwd=ROOT, env=env, check=True)
        # The ordinary compiler output also binds toolchain, dependency and
        # architecture settings that a source revision alone cannot cover.
        # The second link reuses Go's compile cache and changes the LC_UUID
        # for distinct app identities without editing the signed Mach-O.
        ldflags += ' -buildid=' + app_build_id(revision, args.version, bundle_id, args.arch, source_digest, digest(service))
        subprocess.run(['go', 'build', '-trimpath', '-buildvcs=true', '-ldflags', ldflags,
                        '-o', str(service), './cmd/cosmoedge-connect'], cwd=ROOT, env=env, check=True)
        service.chmod(0o755)
        service_metadata.update({'executablePath': APP_SERVICE,
                                 'macOSApp': sign_app(app, service, args, bundle_id)})
        # Keep archived payloads suffixless; the installer registers the
        # one active .app copy with Launch Services.
        app.rename(stage / APP_PAYLOAD)
        service = stage / APP_SERVICE
        shutil.copytree(ROOT / 'integrations/workbuddy/skills/cosmoedge-operations', stage / 'payload/skill',
                        ignore=shutil.ignore_patterns('__pycache__', '*.pyc', '.DS_Store'))
        deploy = ROOT / 'integrations/workbuddy/deploy/macos'
        shutil.copy2(deploy / 'cosmoedge-operations', stage / 'payload/skill/scripts/cosmoedge-operations')
        plugin_metadata = None
        if plugin_source is not None:
            plugin_metadata = package_workbuddy_plugin(stage,
                {'product': 'cosmoedge-connect', 'version': args.version, 'revision': revision, 'modified': dirty,
                 'platform': 'darwin/' + args.arch}, plugin_source)
        (stage / 'payload/skill/candidate.json').write_text(json.dumps({
            'schemaVersion': 1, 'version': args.version, 'revision': revision, 'modified': dirty,
            'platform': 'darwin/' + args.arch, 'serviceSHA256': digest(service),
            'clientFiles': {p.relative_to(stage / 'payload/skill').as_posix(): digest(p)
                            for p in sorted((stage / 'payload/skill/scripts').rglob('*.py'))}}, indent=2) + '\n')
        if args.with_mcp:
            mcp = stage / 'payload/mcp/cosmoedge-mcp'
            mcp.parent.mkdir()
            mcp_flags = ldflags.split(' -buildid=', 1)[0]
            subprocess.run(['go', 'build', '-trimpath', '-buildvcs=true', '-ldflags', mcp_flags,
                            '-o', str(mcp), './cmd/cosmoedge-mcp'], cwd=ROOT, env=env, check=True)
            shutil.copy2(stage / 'payload/skill/candidate.json', mcp.parent / 'candidate.json')
            shutil.copytree(ROOT / 'skills/cosmoedge-operations', stage / 'skills/cosmoedge-operations',
                            symlinks=True, ignore=shutil.ignore_patterns('__pycache__', '*.pyc', '.DS_Store'))
        (stage / 'installer').mkdir()
        shutil.copy2(deploy / 'paired_installer.py', stage / 'installer/paired_installer.py')
        shutil.copy2(deploy / 'install-paired.sh', stage / 'install.command')
        (stage / 'install.command').chmod(0o755)
        shutil.copy2(deploy / 'PAIRED-INSTALL.md', stage / 'README.md')
        for name in ('LICENSE', 'NOTICE'):
            shutil.copy2(ROOT / name, stage / name)
        shutil.copytree(ROOT / 'third_party/licenses', stage / 'third_party/licenses', symlinks=True)
        with zipfile.ZipFile(stage / 'cosmoedge-operations.zip', 'w', zipfile.ZIP_DEFLATED) as archive:
            for path in sorted((stage / 'payload/skill').rglob('*')):
                if path.is_file():
                    archive.write(path, 'cosmoedge-operations/' + path.relative_to(stage / 'payload/skill').as_posix())
        files = []
        for path in sorted(stage.rglob('*')):
            if path.is_symlink():
                raise ValueError('bundle cannot contain symbolic links')
            if path.is_file():
                name = path.relative_to(stage).as_posix()
                role = ('mcp' if name == 'payload/mcp/cosmoedge-mcp' else
                        'mcp-candidate' if name == 'payload/mcp/candidate.json' else
                        'mcp-skill' if name.startswith('skills/cosmoedge-operations/') else
                        'service' if path == service else
                        'service-resource' if name.startswith(APP_PAYLOAD + '/') else
                        'client' if name.startswith('payload/skill/scripts/') and name.endswith('.py') else
                        'workbuddy-plugin' if name.startswith(PLUGIN_PAYLOAD + '/') else
                        'skill' if name.startswith('payload/skill/') else 'installer')
                executable = (role in ('service', 'mcp') or name in ('install.command', 'payload/skill/scripts/cosmoedge-operations')
                              or role == 'workbuddy-plugin' and bool(path.stat().st_mode & 0o111))
                # App permissions were established before signing. Never mutate
                # signed app contents while producing the paired inventory.
                if not name.startswith(APP_PAYLOAD + '/'):
                    path.chmod(0o755 if executable else 0o644)
                files.append({'path': name, 'sha256': digest(path), 'size': path.stat().st_size,
                              'role': role, 'executable': executable})
        manifest = {'schemaVersion': 1, 'product': 'cosmoedge-connect', 'version': args.version,
                    'platform': 'darwin/' + args.arch,
                    'service': service_metadata,
                    'builtAt': datetime.datetime.now(datetime.timezone.utc).isoformat(),
                    'source': {'revision': revision, 'tree': tree, 'modified': dirty, 'filesDigest': source_digest},
                    'files': files}
        if args.with_mcp:
            manifest['mcp'] = {'transport': 'stdio', 'entrypoint': './cmd/cosmoedge-mcp',
                               'executablePath': 'payload/mcp/cosmoedge-mcp', 'candidatePath': 'payload/mcp/candidate.json'}
        if plugin_metadata is not None:
            manifest['workbuddyPlugin'] = plugin_metadata
        (stage / 'manifest.json').write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + '\n')
        (stage / 'source-files.json').write_text(json.dumps(source_files, indent=2) + '\n')
        manifest['source']['inventorySHA256'] = digest(stage / 'source-files.json')
        (stage / 'manifest.json').write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + '\n')
        if (run('git', 'rev-parse', 'HEAD') != revision or source_inventory() != source_files
                or bool(run('git', 'status', '--porcelain', '--untracked-files=normal')) != dirty):
            raise RuntimeError('source changed during build; no paired candidate was emitted')
        stage.rename(output)
        print(json.dumps({'bundle': str(output), 'manifestSHA256': digest(output / 'manifest.json'),
                          'revision': revision, 'modified': dirty, 'version': args.version}, indent=2))
    finally:
        if stage.exists():
            shutil.rmtree(stage)


if __name__ == '__main__':
    main()
